"""Add encrypted PII columns to users table

Revision ID: 69cb9583f7c6
Revises: 81c60ae2d0bd
Create Date: 2026-04-07 07:55:48.385324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69cb9583f7c6'
down_revision = '81c60ae2d0bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_encrypted', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('full_name_encrypted', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('mfa_secret_encrypted', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('address_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_index('idx_user_tenant')
        batch_op.drop_constraint('unique_tenant_email', type_='unique')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_constraint('users_tenant_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])
        batch_op.drop_column('mfa_secret')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_tenant_id_fkey', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('unique_tenant_email', ['tenant_id', 'email'])
        batch_op.create_index('idx_user_tenant', ['tenant_id'], unique=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('address_encrypted')
        batch_op.drop_column('mfa_secret_encrypted')
        batch_op.drop_column('full_name_encrypted')
        batch_op.drop_column('phone_encrypted')

    # ### end Alembic commands ###

