"""initial schema

Revision ID: 81c60ae2d0bd
Revises: a7231945d146
Create Date: 2026-03-31 14:35:52.921828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c60ae2d0bd'
down_revision = 'a7231945d146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('plan', sa.String(length=64), nullable=True))
        batch_op.alter_column('subdomain',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_unique_constraint(None, ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('subdomain',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('plan')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
