#!/usr/bin/env python3
"""
Secret rotation helper (generator only -- does NOT touch live infrastructure).

This tool emits cryptographically strong replacement values for every secret
documented in ``.env.example``. It deliberately:

* Does NOT contact Railway, AWS, Vault, Kubernetes, GitHub, or any other
  secret store. Infrastructure changes remain fully manual.
* Does NOT write to ``.env``, ``.env.production`` or any other file by
  default. Generated values are printed to stdout for the operator to
  copy into their platform's secret UI.
* Does NOT overwrite an existing secret unless the operator passes
  ``--out <path>`` AND ``--force``.
* Does NOT log to files, journald, or system logs.
* Does NOT emit the values to any network destination.

Usage
-----

Print suggested fresh values to stdout (safe default):

    python scripts/rotate_secrets.py

Print a single secret (useful for scripted piping into ``railway variables set``
through stdin without the value appearing in shell history):

    python scripts/rotate_secrets.py --only JWT_SECRET_KEY

Write a new ``.env.rotated`` file locally (never the live ``.env``):

    python scripts/rotate_secrets.py --out .env.rotated

Exit codes
----------

* 0 -- generation succeeded
* 2 -- refused to run (e.g. target file exists without ``--force``)

Security notes
--------------

* Rotating ``ENCRYPTION_KEY`` without re-encrypting stored ciphertexts will
  permanently break decryption of PII fields. Only rotate it inside a
  planned maintenance window that includes a re-encryption step.
* ``BACKUP_ENCRYPTION_KEY`` is intended to be populated with the *previous*
  ``ENCRYPTION_KEY`` during such a window so that the app can decrypt old
  values while re-encrypting with the new key.
* The script runs on any host; values never leave the process's stdout.
  Run it in a trusted shell (no screen recording, no shared tmux session)
  and paste into the platform's secret UI over TLS.
"""

from __future__ import annotations

import argparse
import base64
import os
import secrets
import sys
from pathlib import Path

# name -> (description, generator-callable, format-hint)
SECRET_SPECS: dict[str, tuple[str, callable, str]] = {
    "JWT_SECRET_KEY": (
        "HMAC-SHA256 signing key for JWT access tokens",
        lambda: secrets.token_hex(32),
        "64 hex chars (32 random bytes)",
    ),
    "DASHBOARD_SECRET_KEY": (
        "Flask session cookie signing key for dashboard/flask_dashboard.py",
        lambda: secrets.token_hex(32),
        "64 hex chars (32 random bytes)",
    ),
    "ENCRYPTION_KEY": (
        "AES-256-GCM key for column-level PII encryption",
        lambda: base64.b64encode(secrets.token_bytes(32)).decode("ascii"),
        "base64-encoded 32 bytes",
    ),
    "BACKUP_ENCRYPTION_KEY": (
        "Previous ENCRYPTION_KEY, populated during re-encryption windows",
        lambda: base64.b64encode(secrets.token_bytes(32)).decode("ascii"),
        "base64-encoded 32 bytes",
    ),
    "POSTGRES_PASSWORD": (
        "PostgreSQL password for docker-compose's 'sentinel' role",
        lambda: secrets.token_urlsafe(24),
        "URL-safe 24+ byte random string",
    ),
    "CAPTCHA_SECRET_KEY": (
        "Provider-specific CAPTCHA secret",
        lambda: "REPLACE_WITH_VALUE_FROM_CAPTCHA_PROVIDER",
        "obtain from the CAPTCHA provider dashboard",
    ),
}


def _generate(only: list[str] | None) -> dict[str, str]:
    targets = list(SECRET_SPECS.keys())
    if only:
        unknown = [name for name in only if name not in SECRET_SPECS]
        if unknown:
            print(
                f"error: unknown secret name(s): {', '.join(unknown)}",
                file=sys.stderr,
            )
            print(
                f"known: {', '.join(SECRET_SPECS.keys())}",
                file=sys.stderr,
            )
            sys.exit(2)
        targets = only
    return {name: SECRET_SPECS[name][1]() for name in targets}


def _render_stdout(generated: dict[str, str]) -> None:
    print(
        "# Suggested fresh secret values -- copy into your platform's secret\n"
        "# store (Railway Variables, AWS Secrets Manager, Kubernetes Secret).\n"
        "# This file is not written to disk unless you pass --out.\n"
    )
    for name, value in generated.items():
        description, _, hint = SECRET_SPECS[name]
        print(f"# {description} ({hint})")
        print(f"{name}={value}")
        print()


def _render_file(generated: dict[str, str], out: Path, force: bool) -> None:
    if out.exists() and not force:
        print(
            f"error: refusing to overwrite existing file {out} (pass --force to override)",
            file=sys.stderr,
        )
        sys.exit(2)
    lines = [
        "# Generated by scripts/rotate_secrets.py -- DO NOT COMMIT.\n",
        "# Copy these values into your platform's secret store and then\n",
        "# delete this file. The repository's .gitignore excludes .env*.\n",
        "\n",
    ]
    for name, value in generated.items():
        description, _, hint = SECRET_SPECS[name]
        lines.append(f"# {description} ({hint})\n")
        lines.append(f"{name}={value}\n")
        lines.append("\n")

    # Write with restrictive permissions; never world-readable.
    fd = os.open(
        str(out),
        os.O_WRONLY | os.O_CREAT | (0 if force else os.O_EXCL),
        0o600,
    )
    try:
        with os.fdopen(fd, "w") as fh:
            fh.writelines(lines)
    except Exception:
        os.close(fd)
        raise
    print(f"Wrote {out} with mode 0600. Remove it after uploading to your secret store.")


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Generate fresh secret values. Does not rotate any live "
            "infrastructure -- copy the output into your platform's "
            "secret store manually."
        )
    )
    parser.add_argument(
        "--only",
        nargs="+",
        help="Generate only the named secret(s), e.g. --only JWT_SECRET_KEY",
    )
    parser.add_argument(
        "--out",
        type=Path,
        help="Write generated values to this file (mode 0600) instead of stdout.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Allow --out to overwrite an existing file.",
    )
    args = parser.parse_args()

    generated = _generate(args.only)
    if args.out:
        _render_file(generated, args.out, args.force)
    else:
        _render_stdout(generated)


if __name__ == "__main__":
    main()
